spring:
  application:
    name: :grade-collect
  profiles:
    active: dev
    group:
      local:
        - console-logging
        - file-logging
      dev:
        - console-logging
      prod:
        - console-logging
        - file-logging
  jpa:
    hibernate:
      ddl-auto: none  # ★ 시작 시 항상 테이블 새로 생성
    show-sql: false # true 설정시 JPA 쿼리문 확인 가능
    properties:
      hibernate:
        format_sql: false

server:
  servlet:
    context-path: /
  forward-headers-strategy: framework

