spring:
  datasource:
    url: jdbc:mysql://192.168.123.104:3306/grade_test?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: grade
    password: grade12!@